services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: kakigowhere
      MYSQL_USER: test
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: pw
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: kakigowhere-springboot
    pull_policy: never
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kakigowhere
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: pw
      UPLOAD_DIR: /data/images
      CSV_DIR: /data/csv/
    volumes:
      - app_images:/data/images
      - app_csv:/data/csv

volumes:
  db_data:
  app_images:
  app_csv:
