services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: kakigowhere
      MYSQL_USER: test
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: pw
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pPW" ]
      interval: 10s
      retries: 10
      start_period: 30s

  app:
    image: kakigowhere-springboot
    pull_policy: never
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kakigowhere
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: pw
      UPLOAD_DIR: /data/images
      CSV_DIR: /data/csv/
    volumes:
      - app_images:/data/images
      - app_csv:/data/csv

  frontend:
    image: kakigowhere-react
    pull_policy: never
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"

  flask-ml:
    image: flask-ml
    pull_policy: never
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"
    volumes:
      - app_csv:/data/csv
      - huggingface-cache:/app/cache/huggingface
    environment:
      RAW_CSV: /data/csv/places.csv
      CATEGORISED_CSV: /data/csv/places_categorised.csv
      RAW_RATINGS_CSV: /data/csv/ratings.csv
      KEYWORDS_RATINGS_CSV: /data/csv/ratings_keywords.csv
      HF_HOME: /app/cache/huggingface

volumes:
  db_data:
  app_images:
  app_csv:
  huggingface-cache:
