- name: Deploy Spring Boot app
  hosts: app
  become: yes

  vars:
    docker_image: "docker_username/repo:latest"
    db_user: "user"
    db_pass: "password"
    db_name: "mydb"
    db_root_pass: "rootpassword"

  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        update_cache: yes
        state: present

    - name: Create app directory
      file:
        path: /opt/springboot-app
        state: directory

    - name: Create docker-compose.yml from template
      copy:
        dest: /opt/springboot-app/docker-compose.yml
        content: |
          version: '3.8'

          services:
            db:
              image: mysql:8.0
              restart: always
              environment:
                MYSQL_DATABASE: {{ db_name }}
                MYSQL_USER: {{ db_user }}
                MYSQL_PASSWORD: {{ db_pass }}
                MYSQL_ROOT_PASSWORD: {{ db_root_pass }}
              volumes:
                - db_data:/var/lib/mysql

            app:
              image: {{ docker_image }}
              restart: always
              depends_on:
                - db
              ports:
                - "8080:8080"
              environment:
                SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/{{ db_name }}
                SPRING_DATASOURCE_USERNAME: {{ db_user }}
                SPRING_DATASOURCE_PASSWORD: {{ db_pass }}
                SPRING_JPA_HIBERNATE_DDL_AUTO: update

          volumes:
            db_data:

    - name: Start application
      command: docker compose up -d
      args:
        chdir: /opt/springboot-app
