name: CI Pipeline

on:
  push:
    branches: ['**']

jobs:
  push-checks:
    name: Spotless, Sonatype, JaCoCo, Unit test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Lint (Spotless)
        run: |
          mkdir -p report
          mvn spotless:check > report/spotless-report.txt

      - name: Run SCA (Sonatype)
        if: always()
        run: mvn org.sonatype.ossindex.maven:ossindex-maven-plugin:audit > report/sonatype-report.txt

      - name: Upload Lint and SCA Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-SCA-reports
          path: app/report/

      - name: Run Unit Tests + JaCoCo (Code Coverage)
        if: always()
        run: |
          mkdir -p target
          mvn clean verify surefire-report:report

      - name: Upload JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: app/target/site/jacoco

      - name: Upload Unit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests-report
          path: app/target/reports