name: SCA + Lint + JaCoCo + Unit Test

on:
  push:
    branches-ignore:
      - main

env:
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
  DATABASE_HOST_PORT: ${{ secrets.DATABASE_HOST_PORT }}

jobs:
  push-checks:
    name: Code checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Init fail flag
        run: echo "FAILED=0" >> $GITHUB_ENV

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Lint (Spotless)
        run: |
          mkdir -p target
          mvn spotless:check > target/spotless-report.txt || echo "FAILED=1" >> $GITHUB_ENV

      - name: Run SCA (Sonatype)
        continue-on-error: true
        run: mvn org.sonatype.ossindex.maven:ossindex-maven-plugin:audit > target/sonatype-report.txt || echo "FAILED=1" >> $GITHUB_ENV

      - name: Run Unit Tests + JaCoCo (Code Coverage)
        continue-on-error: true
        run: mvn clean verify || echo "FAILED=1" >> $GITHUB_ENV

      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-reports
          path: |
            target/spotless-report.txt
            target/sonatype-report.txt
            target/site/jacoco

      - name: Fail the job if any step failed
        run: |
          if [ "$FAILED" = "1" ]; then
            echo "At least one check failed. Failing job."
            exit 1
          fi
